name: Node.js CI

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]  # Use a valid Node.js version
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm ci  # Use `npm ci` for faster, reproducible installations
        npm run build --if-present
      env:
        NODE_ENV: development

    - name: Run tests
      run: npm test  # Replace with the appropriate test command
      env:
        NODE_ENV: test

    - name: Check Build Status
      run: |
        if [ $? -eq 0 ]; then
          echo "Build succeeded"
        else
          echo "Build failed"
          exit 1
        fi
